# Real-Estate Price Prediction

A data science project aiming to predict the price of a real-estate in Ames, Iowa.

## 1. Import Required Libraries

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20, 10)

## 2. Loading Datasets

In [3]:
df = pd.read_csv("./house_prices.csv")
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
df.shape

(1460, 81)

## 3. Data Cleaning

The dataset is quite complex with up to 79 explanatory variables describing almost every single aspect of real-estates in Ames, Iowa. We will simplify the data by only including the barebones variables (to determine a house pice) in our analysis, which are:
1. LotArea
2. Neighborhood
3. BedroomAbvGr
4. FullBath
5. HalfBath
6. SalePrice

In [5]:
df1 = df[['LotArea', 'Neighborhood', 'BedroomAbvGr', 'FullBath', 'HalfBath', 'SalePrice']]
df1.head()

LotArea Neighborhood  BedroomAbvGr  FullBath  HalfBath  SalePrice
0     8450      CollgCr             3         2         1     208500
1     9600      Veenker             3         2         0     181500
2    11250      CollgCr             3         2         1     223500
3     9550      Crawfor             3         1         0     140000
4    14260      NoRidge             4         2         1     250000

In [6]:
df1 = df[['LotArea', 'Neighborhood', 'BedroomAbvGr', 'FullBath', 'HalfBath', 'KitchenAbvGr', 'TotalBsmtSF', 'SalePrice']]
df1.head()

LotArea Neighborhood  BedroomAbvGr  FullBath  HalfBath  KitchenAbvGr  \
0     8450      CollgCr             3         2         1             1   
1     9600      Veenker             3         2         0             1   
2    11250      CollgCr             3         2         1             1   
3     9550      Crawfor             3         1         0             1   
4    14260      NoRidge             4         2         1             1   

   TotalBsmtSF  SalePrice  
0          856     208500  
1         1262     181500  
2          920     223500  
3          756     140000  
4         1145     250000

Find any null values.

In [7]:
df1.isnull().sum()

LotArea         0
Neighborhood    0
BedroomAbvGr    0
FullBath        0
HalfBath        0
KitchenAbvGr    0
TotalBsmtSF     0
SalePrice       0
dtype: int64

Find invalid data for each variables.

In [8]:
df1['LotArea'].unique()

array([ 8450,  9600, 11250, ..., 17217, 13175,  9717])

In [9]:
df1['Neighborhood'].unique()

array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
       'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
       'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
       'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
       'Blueste'], dtype=object)

In [10]:
df1['BedroomAbvGr'].unique()

array([3, 4, 1, 2, 0, 5, 6, 8])

In [11]:
df1['FullBath'].unique()

array([2, 1, 3, 0])

In [12]:
df1['HalfBath'].unique()

array([1, 0, 2])

In [13]:
df1['SalePrice'].unique()

array([208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000,
       129900, 118000, 129500, 345000, 144000, 279500, 157000, 132000,
       149000,  90000, 159000, 139000, 325300, 139400, 230000, 154000,
       256300, 134800, 306000, 207500,  68500,  40000, 149350, 179900,
       165500, 277500, 309000, 145000, 153000, 109000,  82000, 160000,
       170000, 130250, 141000, 319900, 239686, 249700, 113000, 127000,
       177000, 114500, 110000, 385000, 130000, 180500, 172500, 196500,
       438780, 124900, 158000, 101000, 202500, 219500, 317000, 180000,
       226000,  80000, 225000, 244000, 185000, 144900, 107400,  91000,
       135750, 136500, 193500, 153500, 245000, 126500, 168500, 260000,
       174000, 164500,  85000, 123600, 109900,  98600, 163500, 133900,
       204750, 214000,  94750,  83000, 128950, 205000, 178000, 118964,
       198900, 169500, 100000, 115000, 190000, 136900, 383970, 217000,
       259500, 176000, 155000, 320000, 163990, 136000, 153900, 181000,
      

In [14]:
df1['KitchenAbvGr'].unique()

array([1, 2, 3, 0])

In [15]:
df1['TotalBsmtSF'].unique()

array([ 856, 1262,  920,  756, 1145,  796, 1686, 1107,  952,  991, 1040,
       1175,  912, 1494, 1253,  832, 1004,    0, 1114, 1029, 1158,  637,
       1777, 1060, 1566,  900, 1704, 1484,  520,  649, 1228, 1234, 1398,
       1561, 1117, 1097, 1297, 1057, 1088, 1350,  840,  938, 1150, 1752,
       1434, 1656,  736,  955,  794,  816, 1842,  384, 1425,  970,  860,
       1410,  780,  530, 1370,  576, 1143, 1947, 1453,  747, 1304, 2223,
        845, 1086,  462,  672, 1768,  440,  896, 1237, 1563, 1065, 1288,
        684,  612, 1013,  990, 1235,  876, 1214,  824,  680, 1588,  960,
        458,  950, 1610,  741, 1226, 1053,  641,  789,  793, 1844,  994,
       1264, 1809, 1028,  729, 1092, 1125, 1673,  728,  732, 1080, 1199,
       1362, 1078,  660, 1008,  924,  992, 1063, 1267, 1461, 1907,  928,
        864, 1734,  910, 1490, 1728,  715,  884,  969, 1710,  825, 1602,
       1200,  572,  774, 1392, 1232, 1572, 1541,  882, 1149,  644, 1617,
       1582,  720, 1064, 1606, 1202, 1151, 1052, 22

The data is already quite clean out-of the box, so not much cleaning was needed.

However, since we have two variables for the number of bathrooms, we may as well merge the FullBath and HalfBath variables by obtaining the sum, store the values into a new column Bathroom, and drop the two former variables.

In [16]:
df1['Bathroom'] = df1.loc[:, ['HalfBath','FullBath']].sum(axis=1)

/var/folders/wz/tf7dxb7n1kn6qkltdtxz4zbw0000gn/T/ipykernel_33481/3879494178.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Bathroom'] = df1.loc[:, ['HalfBath','FullBath']].sum(axis=1)


In [17]:
df1.head()

LotArea Neighborhood  BedroomAbvGr  FullBath  HalfBath  KitchenAbvGr  \
0     8450      CollgCr             3         2         1             1   
1     9600      Veenker             3         2         0             1   
2    11250      CollgCr             3         2         1             1   
3     9550      Crawfor             3         1         0             1   
4    14260      NoRidge             4         2         1             1   

   TotalBsmtSF  SalePrice  Bathroom  
0          856     208500         3  
1         1262     181500         2  
2          920     223500         3  
3          756     140000         1  
4         1145     250000         3

In [18]:
df2 = df1[df1.columns[~df1.columns.isin(['HalfBath','FullBath'])]]
df2.head()

LotArea Neighborhood  BedroomAbvGr  KitchenAbvGr  TotalBsmtSF  SalePrice  \
0     8450      CollgCr             3             1          856     208500   
1     9600      Veenker             3             1         1262     181500   
2    11250      CollgCr             3             1          920     223500   
3     9550      Crawfor             3             1          756     140000   
4    14260      NoRidge             4             1         1145     250000   

   Bathroom  
0         3  
1         2  
2         3  
3         1  
4         3

Add variable area above ground.

In [19]:
df3 = df2.copy()
df3['AreaAboveGr'] = df3.LotArea - df3.TotalBsmtSF
df3.head()

LotArea Neighborhood  BedroomAbvGr  KitchenAbvGr  TotalBsmtSF  SalePrice  \
0     8450      CollgCr             3             1          856     208500   
1     9600      Veenker             3             1         1262     181500   
2    11250      CollgCr             3             1          920     223500   
3     9550      Crawfor             3             1          756     140000   
4    14260      NoRidge             4             1         1145     250000   

   Bathroom  AreaAboveGr  
0         3         7594  
1         2         8338  
2         3        10330  
3         1         8794  
4         3        13115

## 3. Feature Engineering & Outlier Removal

Let's calculate the price per square meter of each real-estate.

In [20]:
df4 = df3.copy()
df4['PriceSqFt'] = df4['SalePrice'] / df4['LotArea']
df4.head()

LotArea Neighborhood  BedroomAbvGr  KitchenAbvGr  TotalBsmtSF  SalePrice  \
0     8450      CollgCr             3             1          856     208500   
1     9600      Veenker             3             1         1262     181500   
2    11250      CollgCr             3             1          920     223500   
3     9550      Crawfor             3             1          756     140000   
4    14260      NoRidge             4             1         1145     250000   

   Bathroom  AreaAboveGr  PriceSqFt  
0         3         7594  24.674556  
1         2         8338  18.906250  
2         3        10330  19.866667  
3         1         8794  14.659686  
4         3        13115  17.531557

Let's focus on the price per square meter variable.

In [21]:
df4.PriceSqFt.describe()

count    1460.000000
mean       21.069878
std        12.387559
min         1.390441
25%        13.775136
50%        17.856628
75%        23.769031
max        95.384615
Name: PriceSqFt, dtype: float64

Remove outliers in PriceSquareM based on the mean and standard deviations. This means that extreme values will not beincluded in our dataframe in order to have a better prediction model.

In [24]:
def remove_pricesqft_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('Neighborhood'):
        m = np.mean(subdf.PriceSqFt)
        st = np.std(subdf.PriceSqFt)
        reduced_df = subdf[ (subdf.PriceSqFt > (m-st)) & (subdf.PriceSqFt <= (m+st)) ]
        df_out = pd.concat([df_out, reduced_df],ignore_index=True)
    return df_out

df5 = remove_pricesqft_outliers(df4)
print("Dataframe shape before outlier removal = ", df4.shape)
print("Dataframe shape after outlier removal = ", df5.shape)
print("Outliers removed =", 1460-1097)

Dataframe shape before outlier removal =  (1460, 9)
Dataframe shape after outlier removal =  (1095, 9)
Outliers removed = 363


Remove variables that are no longer necessary and keep the essential one for building the model for the next stage.

In [78]:
df_a = df5.copy()
df_a = df_a.drop(['TotalBsmtSF', 'AreaAboveGr', 'PriceSqFt'], axis='columns')
df_a.head()

LotArea Neighborhood  BedroomAbvGr  KitchenAbvGr  SalePrice  Bathroom
0     3010      Blmngtn             2             1     167240         2
1     3182      Blmngtn             2             1     192500         2
2     3182      Blmngtn             2             1     192000         2
3     3072      Blmngtn             2             1     178740         2
4     3922      Blmngtn             2             1     194201         2

## 4. Building Models

In [33]:
dummies_nghbd = pd.get_dummies(df_a.Neighborhood)
dummies_nghbd.head(3)

Blmngtn  Blueste  BrDale  BrkSide  ClearCr  CollgCr  Crawfor  Edwards  \
0        1        0       0        0        0        0        0        0   
1        1        0       0        0        0        0        0        0   
2        1        0       0        0        0        0        0        0   

   Gilbert  IDOTRR  ...  NoRidge  NridgHt  OldTown  SWISU  Sawyer  SawyerW  \
0        0       0  ...        0        0        0      0       0        0   
1        0       0  ...        0        0        0      0       0        0   
2        0       0  ...        0        0        0      0       0        0   

   Somerst  StoneBr  Timber  Veenker  
0        0        0       0        0  
1        0        0       0        0  
2        0        0       0        0  

[3 rows x 25 columns]

In [34]:
df_n = pd.concat([df_a,dummies_nghbd],axis='columns')
df_n.head(3)

LotArea Neighborhood  BedroomAbvGr  KitchenAbvGr  SalePrice  Bathroom  \
0     3010      Blmngtn             2             1     167240         2   
1     3182      Blmngtn             2             1     192500         2   
2     3182      Blmngtn             2             1     192000         2   

   Blmngtn  Blueste  BrDale  BrkSide  ...  NoRidge  NridgHt  OldTown  SWISU  \
0        1        0       0        0  ...        0        0        0      0   
1        1        0       0        0  ...        0        0        0      0   
2        1        0       0        0  ...        0        0        0      0   

   Sawyer  SawyerW  Somerst  StoneBr  Timber  Veenker  
0       0        0        0        0       0        0  
1       0        0        0        0       0        0  
2       0        0        0        0       0        0  

[3 rows x 31 columns]

In [37]:
df_n2 = df_n.drop('Neighborhood', axis='columns')
df_n2.head(3)

LotArea  BedroomAbvGr  KitchenAbvGr  SalePrice  Bathroom  Blmngtn  Blueste  \
0     3010             2             1     167240         2        1        0   
1     3182             2             1     192500         2        1        0   
2     3182             2             1     192000         2        1        0   

   BrDale  BrkSide  ClearCr  ...  NoRidge  NridgHt  OldTown  SWISU  Sawyer  \
0       0        0        0  ...        0        0        0      0       0   
1       0        0        0  ...        0        0        0      0       0   
2       0        0        0  ...        0        0        0      0       0   

   SawyerW  Somerst  StoneBr  Timber  Veenker  
0        0        0        0       0        0  
1        0        0        0       0        0  
2        0        0        0       0        0  

[3 rows x 30 columns]

In [38]:
df_n2.shape

(1095, 30)

In [39]:
X = df_n2.drop('SalePrice', axis='columns')
X.head()

LotArea  BedroomAbvGr  KitchenAbvGr  Bathroom  Blmngtn  Blueste  BrDale  \
0     3010             2             1         2        1        0       0   
1     3182             2             1         2        1        0       0   
2     3182             2             1         2        1        0       0   
3     3072             2             1         2        1        0       0   
4     3922             2             1         2        1        0       0   

   BrkSide  ClearCr  CollgCr  ...  NoRidge  NridgHt  OldTown  SWISU  Sawyer  \
0        0        0        0  ...        0        0        0      0       0   
1        0        0        0  ...        0        0        0      0       0   
2        0        0        0  ...        0        0        0      0       0   
3        0        0        0  ...        0        0        0      0       0   
4        0        0        0  ...        0        0        0      0       0   

   SawyerW  Somerst  StoneBr  Timber  Veenker  
0        0        0        0       0        0  
1        0        0        0       0        0  
2        0        0        0       0        0  
3        0        0        0       0        0  
4        0        0        0       0        0  

[5 rows x 29 columns]

In [42]:
y = df_n2.SalePrice
y.head()

0    167240
1    192500
2    192000
3    178740
4    194201
Name: SalePrice, dtype: int64

Creating the train and test datasets.

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

Getting the score of LinearRegression().

In [44]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train, y_train)
lr_clf.score(X_test, y_test)

0.7791609727418985

In [45]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(LinearRegression(), X, y, cv=cv)

array([0.64656494, 0.73324852, 0.74257073, 0.70427591, 0.71373689])

Let's compare the scores of other models.

In [53]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    scores.append({
            'model': 'LinearRegression',
            'best_score': lr_clf.score(X_test, y_test),
            'best_params': None
        })
    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(X,y)


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.158e+11, tolerance: 4.087e+08
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.549e+11, tolerance: 4.286e+08
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iter

model  best_score  \
0             lasso    0.707427   
1     decision_tree    0.654776   
2  LinearRegression    0.779161   

                                         best_params  
0                {'alpha': 2, 'selection': 'random'}  
1  {'criterion': 'friedman_mse', 'splitter': 'best'}  
2                                               None

In conclusion, the linear regression model gives the best score. We'll use this model for later developments.

Now that the model is determined, we can create the function to predict the price.

In [67]:
def predict_price(neighborhood, area, nb_bed, nb_bath, nb_kitch):
    loc_index = np.where(X.columns == neighborhood)[0][0]

    x = np.zeros(len(X.columns))
    x[0] = area
    x[1] = nb_bed
    x[2] = nb_kitch
    x[3] = nb_bath
    if loc_index >= 0:
        x[loc_index] = 1

    return lr_clf.predict([x])[0]

Let's do some test. We'll use Sommerset (as one of the highest valued area) and Timber (as one of the lowest valued area) and compare the results.

In [68]:
predict_price('Somerst', 1000, 2, 2, 1)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


191679.4072032345

In [69]:
predict_price('Somerst', 750, 2, 2, 1)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


190758.1393433773

In [70]:
predict_price('Somerst', 400, 1, 1, 1)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


158044.98478001222

In [71]:
predict_price('Timber', 1000, 2, 2, 1)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


184115.09105738893

In [72]:
predict_price('Timber', 750, 2, 2, 1)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


183193.82319753175

In [73]:
predict_price('Timber', 400, 1, 1, 1)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


150480.6686341667

The results are coherent so the prediction function works as expected!

## 5. Creating the Web App

We'll implement this estimator as a web app with the help of Streamlit. The full implementation can be found as "PredictorApp.py" and can be launched!

In [77]:
import streamlit as st

st.title("Real-Estate Price Estimator")
st.header("With the help of AI and Machine Learning, find the best estimate for your real-estate in Ames, Iowa.")

col1, col2 = st.columns(2)

list_neighborhoods = ('Bloomington Heights',
'Bluestem',
'Briardale',
'Brookside',
'Clear Creek',
'College Creek',
'Crawford',
'Edwards',
'Gilbert',
'Iowa DOT and Rail Road',
'Meadow Village',
'Mitchell',
'North Ames',
'Northridge',
'Northpark Villa',
'Northridge Heights',
'Northwest Ames',
'Old Town',
'South & West of Iowa State University',
'Sawyer',
'Sawyer West',
'Somerset',
'Stone Brook',
'Timberland',
'Veenker')

with col1:
    area_sqft = st.number_input(
        "Total area (in square feet)"
    )
    neigh =  st.selectbox(
        "Neighborhood",
        list_neighborhoods
    )

match neigh:
    case 'Bloomington Heights':
        neigh = 'Blmngtn'
    case 'Bluestem':
        neigh = 'Blueste'
    case 'Briardale':
        neigh = 'BrDale'
    case 'Brookside':
        neigh = 'BrkSide'
    case 'Clear Creek':
        neigh = 'ClearCr'
    case 'College Creek':
        neigh = 'CollgCr'
    case 'Crawford':
        neigh = 'Crawfor'
    case 'Edwards':
        neigh = 'Edwards'
    case 'Gilbert':
        neigh = 'Gilbert'
    case 'Iowa DOT and Rail Road':
        neigh = 'IDOTRR'
    case 'Meadow Village':
        neigh = 'MeadowV'
    case 'Mitchell':
        neigh = 'Mitchel'
    case 'North Ames':
        neigh = 'Names'
    case 'Northridge':
        neigh = 'NoRidge'
    case 'Northpark Villa':
        neigh = 'NPkVill'
    case 'Northridge Heights':
        neigh = 'NridgHt'
    case 'Northwest Ames':
        neigh = 'NWAmes'
    case 'Old Town':
        neigh = 'OldTown'
    case 'South & West of Iowa State University':
        neigh = 'SWISU'
    case 'Sawyer':
        neigh = 'Sawyer'
    case 'Sawyer West':
        neigh = 'SawyerW'
    case 'Somerset':
        neigh = 'Somerst'
    case 'Stone Brook':
        neigh = 'StoneBr'
    case 'Timberland':
        neigh = 'Timber'
    case 'Veenker':
        neigh = 'Veenker'

with col2:
    nb_bedroom = st.slider('Number of bedrooms', 0, 15, 2)
    nb_bathroom = st.slider('Number of bedrooms', 0, 30, 2)
    nb_kitchen = st.slider('Number of kitchen', 0, 10, 1)

price = predict_price(neigh, float(area_sqft), nb_bedroom, nb_kitchen, nb_bathroom)

if st.button('Calculate'):
    st.write('The price is $', price)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
